@startuml
class DataHandler {
    -List<HashMap<>> data
    -String LNAME
    -String FNAME
    -String SAL

    +getDataFromFile()
    +displayDataFromFileTabular()
    +ArrayList<HashMap<String,String>> returnArrayListWithData()
}
@enduml