@startuml
Class Solution46 {
    main(Args[])
}
Class DataHandler {
    -HashMap data

    +getInputFromTxtFile()
    +outputHistogramAsGreatestToLeast()
    -sortDataByValue()
    -outputDataToFileAsTabularHistogram()
    +returnDataFromHashMap()
}
Solution46 -- DataHandler
@enduml