@startuml
class DataHandler {
    -List data

    +void getDataFromFile()
    +void sortDataAlphabetically()
    +void printDataTotalNumberOfNamesAndDataToFile()
    -void printNumberOfNamesToFile()
    -void printDataToFile()
    -FileWriter initializeFilePointer()
    +ArrayList<String> returnArrayListOfDataAsList()
}
@enduml