@startuml
class DataHandler {
    -List data

    +void getDataFromFile()
    +void displayNumberOfNames()
    +void displayData()
    +void sortDataAlphabetically()
    +ArrayList<String> returnArrayListOfDataAsList()
}
@enduml