@startuml
class Solution45 {
    main(String Args[])
}
class DataHandler {
    -StringBuilder data

    +getDataFromTextFile()
    -replaceUtilizeWithUseInDataString()
    +returnStringData()
    +generateOutputFile()
}
Solution45 -- DataHandler
@enduml